name: First workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greetings
        run: echo "Hello Greetings"
      - name: Print By bye
        run: echo "Bye bye thanks"
        
